;;; Color theme based on Tango Palette.
;;; Created by zhuqin <zhuqin83@gmail.com>
;; color plate
;; Butter       fce94f  edd400  c4a000
;; Orange       fcaf3e  f57900  ce5c00
;; Chocolate    e9b96e  c17d11  8f5902
;; Chameleon    8ae234  73d216  4e9a06
;; Sky Blue     729fcf  3465a4  204a87
;; Plum         ad7fa8  75507b  5c3566
;; Scarlet Red  ef2929  cc0000  a40000
;; Aluminium    eeeeec  d3d7cf  babdb6
;;              888a85  555753  2e3436
(defvar cool-fg       "#000000")
(defvar cool-bg       "#EDEDED")
(defvar cool-grey     "#DEDFDF")
(defvar cool-green-0  "#4CB64A")
(defvar cool-yellow-0 "#FEFFBF")
(defvar cool-yellow-1 "#F8D00E")
(defvar cool-red-0    "#f5666d")
(defvar cool-pink-0   "#F74D97")
(defvar cool-pink-1   "#FA519A")
(defvar cool-pink-2   "#FD8DBD")
(defvar cool-purple-0 "#a8799c")
(defvar cool-blue-0   "#5179B5")
(defvar cool-blue-1   "#4F78B5")
(defvar cool-blue-2   "#1C3C79")
(defvar cool-blue-3   "#1C3C79")

(defvar fedora-blue-0  "#00BBFF")
(defvar fedora-blue-1  "#0084C8")
(defvar fedora-blue-2  "#00578E")
(defvar fedora-pink-0  "#FF8CA7")
(defvar fedora-pink-1  "#FF7092")
(defvar fedora-green-0 "#9CBB43")
(defvar fedora-green-1 "#9CBB43")


;;; Tango light theme
(defun color-theme-tango-light ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-tango-light
     (
      ;;(background-color . "#ffffff")
      (background-mode . light)
      (border-color . "#eeeeec")
      (cursor-color . "#3465a4")
      ;;(foreground-color . "#1a1a1a")
      ;;(mouse-color . "#8ae234")
      )
     ((help-highlight-face . underline)
      ;;(ibuffer-dired-buffer-face ((t (:foreground "#3465a4"))))
      ;;(ibuffer-help-buffer-face . font-lock-comment-face)
      ;;(ibuffer-hidden-buffer-face . font-lock-warning-face)
      ;;(ibuffer-occur-match-face . font-lock-warning-face)
      ;;(ibuffer-read-only-buffer-face ((t (:foreground "#75507b"))))
      ;;(ibuffer-special-buffer-face . font-lock-keyword-face)
      ;;(ibuffer-title-face . font-lock-type-face)
      )
     (fringe ((t (:background "#eeeeec"))))
     (mode-line ((t (:foreground "#ffffff" :background "#3465a4" :box (:style released-button)))))
     ;;(mode-line-inactive ((t (:foreground "#cccddd" :background "#111111"))))
     ;;(region ((t (:background "#fce94f"))))    ;; Chenbin Deleted <2010-02-20 08:31:10>
     (region ((t (:background "#fce94f"))))
     ;;(flyspell-duplicate ((t (:foreground "#fcaf3e"))))
     ;;(flyspell-incorrect ((t (:foreground "#cc0000"))))
     (font-latex-math-face ((t (:foreground "#8f5902"))))
     (font-latex-sedate-face ((t (:foreground "#204a87"))))
     ;;(font-latex-string-face ((t (:foreground "#4e9a06"))))
     ;;(font-latex-warning-face ((t (:foreground "#ef2929" :bold t))))
     (font-lock-builtin-face ((t (:foreground "#3465a4"))))
     (font-lock-comment-face ((t (:foreground "#f57900"))))
     (font-lock-constant-face ((t (:foreground "#c4a000" :bold t))))
     (font-lock-doc-face ((t (:foreground "#c17d11"))))
     (font-lock-keyword-face ((t (:foreground "#ce5c00" :bold t))))
     (font-lock-type-face ((t (:foreground "#5c3566" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#4e9a06" :bold t))))
     (font-lock-warning-face ((t (:foreground "#ef2929" :bold t))))
     (font-lock-function-name-face ((t (:foreground "#3465a4" :bold t))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (font-lock-string-face ((t (:foreground "#75507b"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:background "#e9b96e" :foreground "#2e3436"))))
     ;;(paren-face-match ((t (:inherit show-paren-match-face))))
     ;;(paren-face-match-light ((t (:inherit show-paren-match-face))))
     ;;(paren-face-mismatch ((t (:inherit show-paren-mismatch-face))))
     ;;(persp-selected-face ((t (:foreground "#729fcf"))))
     ;;(show-paren-match-face ((t (:background "#73d216"))))
     (show-paren-match-face ((t (:background "#00ee76"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     ;;(org-date ((t (:foreground "LightSteelBlue" :underline t))))
     ;;(org-hide ((t (:foreground "#2e3436"))))
     (org-todo ((t (:inherit font-lock-warning-face))))
     (org-level-1 ((t (:foreground "#3465a4"))))
     (org-level-2 ((t (:foreground "#4e9a06"))))
     (org-level-3 ((t (:foreground "#ce5c00"))))
     (org-level-4 ((t (:inherit font-lock-doc-face))))
     (org-level-5 ((t (:foreground "#5c3566"))))
     (org-level-6 ((t (:foreground "#c4a000"))))
     (org-level-7 ((t (:inherit font-lock-string-face))))
     ;;(org-level-8 ((t (:inherit font-lock-type-face :bold t))))
     ;;(org-link ((t (:foreground "#204a87" :underline t))))

     (minibuffer-prompt ((t (:foreground "#3465a4" :bold t))))
     (info-xref ((t (:foreground "#3465a4"))))
     (info-xref-visited ((t (:foreground "#75507b"))))
     (highlight ((t (:background "#d3d7cf"))))
     )))


;;; color-theme-tango-2
(defun color-theme-tango-2 ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-tango-2
     ((background-color . "#121212")
      (background-mode . dark)
      (border-color . "#888a85")
      (foreground-color . "#eeeeec")
      (cursor-color . "#888888")
      (mouse-color . "#333333"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-constant-face ((t (:foreground "#ad7fa8"))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-function-name-face ((t (:foreground "#729fcf"))))
     (font-lock-keyword-face ((t (:foreground "#fcaf3e"))))
     (font-lock-string-face ((t (:foreground "#73d216"))))
     (font-lock-type-face ((t (:foreground "#c17d11"))))
     (font-lock-variable-name-face ((t (:foreground "#fce94f"))))
     (font-lock-warning-face ((t (:bold t :foreground "#cc0000"))))

     (border ((t (:background "#888a85"))))
     (fringe ((t (:background "#111111"))))
     (highlight ((t (:background "#444444"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#2e3436"))))
     (mode-line-inactive ((t (:foreground "#cccddd" :background "#111111"))))
     (region ((t (:background "#555753"))))

     (flyspell-duplicate ((t (:foreground "#fcaf3e"))))
     (flyspell-incorrect ((t (:foreground "#cc0000"))))

     (org-date ((t (:foreground "LightSteelBlue" :underline t))))
     (org-hide ((t (:foreground "#2e3436"))))
     (org-todo ((t (:inherit font-lock-keyword-face :bold t))))
     (org-level-1 ((t (:inherit font-lock-function-name-face))))
     (org-level-2 ((t (:inherit font-lock-variable-name-face))))
     (org-level-3 ((t (:inherit font-lock-keyword-face))))
     (org-level-4 ((t (:inherit font-lock-string-face))))
     (org-level-5 ((t (:inherit font-lock-constant-face))))

     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (paren-face-match ((t (:inherit show-paren-match-face))))
     (paren-face-match-light ((t (:inherit show-paren-match-face))))
     (paren-face-mismatch ((t (:inherit show-paren-mismatch-face))))
     (persp-selected-face ((t (:foreground "#729fcf"))))
     (show-paren-match-face ((t (:background "#729fcf" :foreground "#eeeeec"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#729fcf"))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     )))


;; color-theme-darkmate.el --- The DarkMate Color Theme for Emacs.

;; The DarkMate color theme for Emacs is a color scheme samiliar with the
;; DarkMate color theme of gEdit. It depends on the color-theme.el which is in
;; the color-theme package for Emacs.
;;
;; Usage:
;; Add the following to your .emacs file (requires the color-theme package):
;;
;; (require 'color-theme)
;; (color-theme-initialize)
;; (load-file "~/.emacs.d/themes/color-theme-darkmate.el")
;;
;; and then evaluate (color-theme-darkmate) to activate it.
;;
;; This is free software; you can redistribute it and/or modify it under the
;; terms of the GNU General Public License as published by the Free Software
;; Foundation; either version 2, or (at your option) any later version.
;; Created by wwliu <wenstream@gmail.com>, 2009-02-09.

;; Code:

(defun color-theme-darkmate ()
  "A color theme inspired by the DarkMate color theme of gEdit, which is
inspired by the default color theme of TextMate.
Created by wwliu <wenstream@gmail.com>, 2009-02-09."
  (interactive)
;; (color-ambra "#ff9900")
;; (color-asfalto "#555753")
;; (color-carbon "#232323")
;; (color-lime "#96ff00")
;; (color-purple "#bb66ff")
;; (color-violet "#9e91ff")
;; (color-white "#eeeeee")
;; (color-yellow "#fce94f")
  (color-theme-install
   '(color-theme-darkmate
     ((background-color . "#232323")
      (foreground-color . "#eeeeee")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#eeeeee")
      (mouse-color . "sienna1"))
     (default ((t (:background "#232323" :foreground "#eeeeee"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :italic t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (font-lock-builtin-face ((t (:foreground "cyan"))))
     (font-lock-comment-face ((t (:foreground "#bb66ff" :italic t))))
     (font-lock-constant-face ((t (:foreground "#fce94f"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#9e91ff"))))
     (font-lock-keyword-face ((t (:bold t :foreground "#ff9900"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine" :bold t))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))

     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))

     (font-lock-string-face ((t (:foreground "#96ff00"))))
     (font-lock-type-face ((t (:foreground "#8DA6CE"))))
     (font-lock-variable-name-face ((t (:foreground "#FF6400"))))
     (font-lock-warning-face ((t (:foreground "Pink" :bold t))))
     (region ((t (:background "#555753"))))
     (mode-line ((t (:background "#101010" :foreground "white" :box (:line-width -1 :color "#606060") :weight semi-bold :bold t))))
     (mode-line-inactive ((t (:background "#404040" :foreground "gray72" :box (:line-width -1 :color "#606060")))))
     (modeline-buffer-id ((t (:background "#101010" :foreground "white"))))
     (modeline-mousable ((t (:background "#101010" :foreground "white"))))
     (modeline-mousable-minor-mode ((t (:background "#101010" :foreground "white"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "white"))))
     (underline ((t (:underline t))))
     (toolbar ((t (nil))))
     (setnu-line-number-face ((t (:background "Grey15" :foreground "#555753" :bold t))))
     (show-paren-match-face ((t (:background "#bb66ff" :foreground "#eeeeee" :bold t))))
     (zmacs-region ((t (:background "snow" :foreground "ble")))))))


;;; Color theme based on Tango Palette. Created by danranx@gmail.com
(defun color-theme-tango ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-tango
     ((background-color . "#2e3436")
      (background-mode . dark)
      (border-color . "#888a85")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "#8ae234"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (border ((t (:background "#888a85"))))
     (fringe ((t (:background "grey10"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#555753"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-constant-face ((t (:foreground "#8ae234"))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf" :bold t))))
     (font-lock-string-face ((t (:foreground "#ad7fa8" :italic t))))
     (font-lock-type-face ((t (:foreground "#8ae234" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900"))))
     (font-lock-function-name-face ((t (:foreground "#edd400" :bold t :italic t))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (show-paren-match-face ((t (:foreground "#2e3436" :background "#73d216"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     )))


(defun color-theme-gnome-3-adwaita ()
  "Gnome 3 color theme"
  (interactive)
  (color-theme-install
   (append
    (list 'color-theme-gnome-3-adwaita
          `((background-color . ,cool-bg)
            (background-mode . light)
            (border-color . ,cool-bg)
            (cursor-color . ,fedora-blue-1)
            (foreground-color . ,cool-fg)
            (mouse-color . "black"))
          `(fringe ((t (:background ,cool-bg))))
          `(mode-line ((t (:foreground ,cool-fg :background "white"))))
          ;; `(mode-line-buffer-id ((t (:bold t :foreground ,cool-yellow-1))))
          `(mode-line-inactive ((t (:foreground ,cool-grey :background ,"white"))))
          `(minibuffer-prompt ((t (:foreground ,fedora-blue-1 :bold t))))
          `(region ((t (:background ,cool-yellow-0))))
          `(dired-header ((t (:bold t :foreground ,fedora-blue-1))))

          `(font-lock-builtin-face ((t (:bold t :foreground ,cool-red-0))))
          `(font-lock-comment-face ((t (:foreground ,cool-green-0))))
          `(font-lock-constant-face ((t (:foreground ,cool-red-0))))
          `(font-lock-doc-face ((t (:foreground ,cool-green-0 :bold t))))
          `(font-lock-function-name-face ((t (:foreground ,fedora-blue-2 :bold t))))
          `(font-lock-keyword-face ((t (:bold t :foreground ,cool-blue-0))))
          `(font-lock-preprocessor-face ((t (:foreground ,cool-fg))))
          `(font-lock-string-face ((t (:foreground ,fedora-pink-1))))
          `(font-lock-type-face ((t (:foreground ,cool-pink-0 :bold t))))
          `(font-lock-variable-name-face ((t (:foreground ,fedora-blue-1 :bold t))))
          `(font-lock-warning-face ((t (:foreground ,cool-red-0 :bold t))))
          ;;js2-external-variable

          `(erc-action-face ((t (:foreground ,cool-red-0))))
          `(erc-button ((t (:foreground ,cool-purple-0))))
          `(erc-current-nick-face ((t (:bold t :foreground ,fedora-pink-1))))
          `(erc-error-face ((t (:foreground ,cool-red-0 :bold t))))
          `(erc-input-face ((t (:foreground ,cool-fg))))
          `(erc-keyword-face ((t (:foreground ,cool-red-0))))
          `(erc-my-nick-face ((t (:bold t :foreground ,fedora-pink-0))))
          `(erc-nick-default-face ((t (:bold t :foreground ,fedora-blue-1))))
          `(erc-notice-face ((t (:foreground ,fedora-blue-1))))
          `(erc-prompt-face ((t (:foreground ,cool-fg))))
          `(erc-timestamp-face ((t (:foreground ,cool-green-0))))

          `(magit-log-sha1 ((t (:foreground ,fedora-pink-1))))
          `(magit-log-head-label-local ((t (:foreground ,cool-blue-1))))
          `(magit-log-head-label-remote ((t (:foreground ,cool-green-0))))
          `(magit-branch ((t (:bold t :foreground ,fedora-blue-1))))
          `(magit-section-title ((t (:bold t :foreground ,fedora-blue-2))))
          `(magit-item-highlight ((t (:background ,cool-yellow-0))))
          `(magit-diff-add ((t (:bold t :foreground ,cool-green-0))))
          `(magit-diff-del ((t (:bold nil :foreground ,cool-red-0))))

          `(gnus-group-mail-1-empty ((t (:foreground ,fedora-blue-2))))
          `(gnus-group-mail-1 ((t (:bold t :foreground ,cool-blue-1))))
          `(gnus-group-mail-2-empty ((t (:foreground ,fedora-blue-2))))
          `(gnus-group-mail-2 ((t (:bold t :foreground ,fedora-green-0))))
          `(gnus-group-news-3-empty ((t (:foreground ,fedora-blue-2))))
          `(gnus-group-news-3 ((t (:bold t :foreground ,fedora-green-1))))
          `(gnus-header-name ((t (:bold t :foreground ,fedora-blue-1))))
          `(gnus-header-subject ((t (:bold t :foreground ,fedora-pink-1))))
          `(gnus-header-content ((t (:foreground ,fedora-pink-1))))
          `(gnus-button ((t (:bold t :foreground ,fedora-blue-2))))
          `(gnus-cite-1 ((t (:foreground ,fedora-blue-2))))
          `(gnus-cite-2 ((t (:foreground ,fedora-blue-1))))
          `(widget-button ((t (:bold t :foreground ,fedora-blue-1))))
          ;;`(diff-header ((t (:foreground ,cool-fg))))
          `(diff-added ((t (:bold t :foreground ,cool-green-0))))
          `(diff-removed ((t (:bold t :foreground ,cool-red-0))))

          `(w3m-anchor ((t (:bold t :foreground ,cool-pink-1))))
          ))))


(defun color-theme-cool-dark ()
  "Cool Dark Theme"
  (interactive)
  (color-theme-install
   (append
    (list 'color-theme-cool-dark
          `((background-color . ,cool-bg)
            (background-mode . dark)
            (border-color . ,cool-bg)
            (cursor-color . ,cool-green-0)
            (foreground-color . ,cool-fg)
            (mouse-color . "black"))
          `(fringe ((t (:background ,cool-bg))))
          `(mode-line ((t (:foreground ,cool-pink-1 :background "black"))))
          ;; `(mode-line-buffer-id ((t (:bold t :foreground ,cool-yellow-1))))
          `(mode-line-inactive ((t (:foreground ,cool-green-0 :background "black"))))
          `(minibuffer-prompt ((t (:foreground ,cool-blue-1 :bold t))))
          `(region ((t (:background ,cool-blue-3))))

          `(font-lock-builtin-face ((t (:bold t :foreground ,cool-red-0))))
          `(font-lock-comment-face ((t (:foreground ,cool-yellow-0))))
          `(font-lock-constant-face ((t (:foreground ,cool-red-0))))
          `(font-lock-doc-face ((t (:foreground ,cool-yellow-0))))
          `(font-lock-function-name-face ((t (:foreground ,cool-blue-0))))
          `(font-lock-keyword-face ((t (:bold t :foreground ,cool-yellow-1))))
          `(font-lock-preprocessor-face ((t (:foreground ,cool-fg))))
          `(font-lock-string-face ((t (:foreground ,cool-pink-2))))
          `(font-lock-type-face ((t (:foreground ,cool-pink-0 :bold t))))
          `(font-lock-variable-name-face ((t (:foreground ,cool-blue-2))))
          `(font-lock-warning-face ((t (:foreground ,cool-red-0 :bold t))))

          `(erc-action-face ((t (:foreground ,cool-red-0))))
          `(erc-button ((t (:foreground ,cool-purple-0))))
          `(erc-current-nick-face ((t (:foreground ,cool-pink-2))))
          `(erc-error-face ((t (:foreground ,cool-red-0 :bold t))))
          `(erc-input-face ((t (:foreground ,cool-fg))))
          `(erc-keyword-face ((t (:foreground ,cool-red-0))))
          `(erc-my-nick-face ((t (:foreground ,cool-blue-0))))
          `(erc-nick-default-face ((t (:bold t :foreground ,cool-pink-1))))
          `(erc-notice-face ((t (:foreground ,cool-blue-2))))
          `(erc-prompt-face ((t (:foreground ,cool-fg))))
          `(erc-timestamp-face ((t (:foreground ,cool-green-0))))

          `(magit-log-sha1 ((t (:foreground "#cf6a4c"))))
          `(magit-log-head-label-local ((t (:foreground "#3387cc"))))
          `(magit-log-head-label-remote ((t (:foreground "#65b042"))))
          `(magit-branch ((t (:bold t :foreground ,cool-yellow-1))))
          `(magit-section-title ((t (:bold t :foreground ,cool-pink-0))))
          `(magit-item-highlight ((t (:background "#1f1f1f"))))
          `(magit-diff-add ((t (:bold t :foreground ,cool-green-0))))
          `(magit-diff-del ((t (:bold nil :foreground ,cool-red-0))))

          `(gnus-group-mail-1-empty ((t (:foreground ,cool-pink-1))))
          `(gnus-group-mail-1 ((t (:bold t :foreground ,cool-pink-1))))
          `(gnus-group-mail-3-empty ((t (:foreground ,cool-blue-0))))
          `(gnus-group-mail-3 ((t (:bold t :foreground ,cool-pink-1))))
          `(gnus-group-news-3-empty ((t (:foreground ,cool-blue-2))))
          `(gnus-group-news-3 ((t (:bold t :foreground ,cool-green-0))))

          `(w3m-anchor ((t (:bold t :foreground ,cool-pink-1))))
          ))))

(defun color-theme-deep-blue-up ()
   "Color theme by Tomas Cerha, created 2001-11-13.
    Modify by Chenbin"
   (interactive)
   (color-theme-install
    '(color-theme-deep-blue
      ((background-color . "#102e4e")
       (background-mode . dark)
       (border-color . "black")
       (cursor-color . "green")
       (foreground-color . "#eeeeee")
       (mouse-color . "white"))
      ((browse-kill-ring-separator-face . bold)
       (display-time-mail-face . mode-line)
       (help-highlight-face . underline)
       (list-matching-lines-face . secondary-selection)
       (vc-annotate-very-old-color . "#0046FF")
       (view-highlight-face . highlight)
       (widget-mouse-face . highlight))
      (default ((t (:stipple nil :background "#102e4e" :foreground "#eeeeee" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "misc-fixed"))))
      (Info-title-1-face ((t (:bold t :weight bold :family "helv" :height 1.728))))
      (Info-title-2-face ((t (:bold t :family "helv" :weight bold :height 1.44))))
      (Info-title-3-face ((t (:bold t :weight bold :family "helv" :height 1.2))))
      (Info-title-4-face ((t (:bold t :family "helv" :weight bold))))
      (bold ((t (:bold t :weight bold))))
      (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
      (border ((t (:background "black"))))
      (calendar-today-face ((t (:background "blue"))))
      (change-log-acknowledgement-face ((t (:italic t :slant italic :foreground "CadetBlue"))))
      (change-log-conditionals-face ((t (:foreground "SeaGreen2"))))
      (change-log-date-face ((t (:foreground "burlywood"))))
      (change-log-email-face ((t (:foreground "SeaGreen2"))))
      (change-log-file-face ((t (:bold t :weight bold :foreground "goldenrod"))))
      (change-log-function-face ((t (:foreground "SeaGreen2"))))
      (change-log-list-face ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
      (change-log-name-face ((t (:foreground "gold"))))
      (comint-highlight-input ((t (:bold t :weight bold))))
      (comint-highlight-prompt ((t (:foreground "cyan"))))
      (cursor ((t (:background "green" :foreground "black"))))
      (cvs-filename-face ((t (:foreground "lightblue"))))
      (cvs-handled-face ((t (:foreground "pink"))))
      (cvs-header-face ((t (:bold t :foreground "lightyellow" :weight bold))))
      (cvs-marked-face ((t (:bold t :foreground "green" :weight bold))))
      (cvs-msg-face ((t (:italic t :slant italic))))
      (cvs-need-action-face ((t (:foreground "orange"))))
      (cvs-unknown-face ((t (:foreground "red"))))
      (diary-face ((t (:foreground "orange red"))))
      (diff-added-face ((t (nil))))
      (diff-changed-face ((t (nil))))
      (diff-context-face ((t (:foreground "grey70"))))
      (diff-file-header-face ((t (:bold t :background "grey60" :weight bold))))
      (diff-function-face ((t (:foreground "grey70"))))
      (diff-header-face ((t (:background "grey45"))))
      (diff-hunk-header-face ((t (:background "grey45"))))
      (diff-index-face ((t (:bold t :weight bold :background "grey60"))))
      (diff-nonexistent-face ((t (:bold t :weight bold :background "grey60"))))
      (diff-removed-face ((t (nil))))
      (fixed-pitch ((t (:family "fixed"))))
      (font-latex-bold-face ((t (:bold t :foreground "OliveDrab" :weight bold))))
      (font-latex-italic-face ((t (:italic t :foreground "OliveDrab" :slant italic))))
      (font-latex-math-face ((t (:foreground "burlywood"))))
      (font-latex-sedate-face ((t (:foreground "LightGray"))))
      (font-latex-string-face ((t (:foreground "LightSalmon"))))
      (font-latex-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
      (font-lock-builtin-face ((t (:foreground "LightCoral"))))
      (font-lock-comment-face ((t (:italic t :foreground "CadetBlue" :slant italic))))
      (font-lock-constant-face ((t (:foreground "gold"))))
      (font-lock-doc-face ((t (:foreground "BlanchedAlmond"))))
      (font-lock-doc-string-face ((t (:bold t :foreground "BlanchedAlmond"))))
      (font-lock-function-name-face ((t (:bold t :italic t :foreground "goldenrod" :weight bold))))
      (font-lock-keyword-face ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
      (font-lock-preprocessor-face ((t (:foreground "gold"))))
      (font-lock-reference-face ((t (:foreground "LightCoral"))))
      (font-lock-string-face ((t (:foreground "burlywood"))))
      (font-lock-type-face ((t (:bold t :foreground "CadetBlue1"))))
      (font-lock-variable-name-face ((t (:bold t :foreground "SeaGreen2"))))
      (font-lock-warning-face ((t (:foreground "yellow"))))
      (fringe ((t (:background "#405060"))))
      (header-line ((t (:box (:line-width 2 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
      (highlight ((t (:background "darkgreen"))))
      (holiday-face ((t (:foreground "green"))))
      (info-header-node ((t (:foreground "DeepSkyBlue1"))))
      (info-header-xref ((t (:bold t :weight bold :foreground "SeaGreen2"))))
      (info-menu-5 ((t (:foreground "wheat"))))
      (info-menu-header ((t (:bold t :family "helv" :weight bold))))
      (info-node ((t (:foreground "DeepSkyBlue1"))))
      (info-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
      (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
      (isearch-lazy-highlight-face ((t (:background "paleturquoise4"))))
      (italic ((t (:italic t :slant italic))))
      (menu ((t (:background "gray" :foreground "black" :family "helvetica"))))
      (modeline ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
      (modeline-buffer-id ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
      (modeline-mousable ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
      (modeline-mousable-minor-mode ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
      (mouse ((t (:background "white"))))
      (region ((t (:background "DarkCyan"))))
      (scroll-bar ((t (:background "gray" :foreground "#506070"))))
      (secondary-selection ((t (:background "yellow" :foreground "gray10"))))
      (show-paren-match-face ((t (:bold t :foreground "yellow" :weight bold))))
      (show-paren-mismatch-face ((t (:bold t :foreground "red" :weight bold))))
      (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
      (tooltip ((t (:background "lightyellow" :foreground "black"))))
      (trailing-whitespace ((t (:background "#102e4e"))))
      (underline ((t (:underline t))))
      (variable-pitch ((t (:family "helv"))))
      (widget-button-face ((t (:bold t :weight bold))))
      (widget-button-pressed-face ((t (:foreground "red"))))
      (widget-documentation-face ((t (:foreground "lime green"))))
      (widget-field-face ((t (:background "dim gray"))))
      (widget-inactive-face ((t (:foreground "light gray"))))
      (widget-single-line-field-face ((t (:background "dim gray")))))))


(provide 'yoyo-themes)
